Added ability to specifying an eval statement for tabular data input. Useful for use cases such as combining multiple RFs to create a stress for comparison
nasa/abaverify pull request #2
Opened 2018-10-02 19:35 UTC by stewartboyd119

The eval statement allows a user to specify some combination
of ABAQUS historical data. The user specifies, in a normal fashion,
dictionaries definining how to interrogate the abaqus data with
a dictionary in the identifier list. The difference being that
an extra key value pair is provided *av_id* . This is a unique
identifier of the identifying object so that it may be referenced in
either the x_eval_statement or y_eval_statement (additional key, vals
in an element of results list).

x and y eval statements are strings which define a valid
python syntax equation for somehow combining the xy hist
data returned by the identifier. Internally a dictionary
d is defined mapping labels -> xydata.

Therefore an eval statement would be written as follows:

d['label1'] + d['label2']

2018-10-05 12:23 UTC, acbergan requested changes
Looks great in general! How do you feel about making the 'eval' stuff general so that it can be used with other results types? If you don't have the bandwidth to take this change on now, I'll accept the PR as is. Just a couple of nit-picks.

2018-10-05 12:23 UTC, acbergan commented on readme.md
> +list of tuples (specified as referenceValue). Additionally, a more advanced usage is allowed within the tabular option to specify a pythonic statement for combinging
I think a ')' is missing here.

2018-10-05 12:23 UTC, acbergan commented on readme.md
> +            "xEvalStatement": "(d['x1'] + d['x2']) / (2 * {l})".format(l=l),
Please rename 'l' since it looks almost identical to 1.

2018-10-05 12:23 UTC, acbergan commented on abaverify/processresults.py
> +    debug(fileName)
Is this needed?

2018-10-07 20:25 UTC, stewartboyd119 commented
Generalized eval for other result types. Added eval test for max/min. Didn't do it initially for other result types as I didn't see a non eval equivalent in the test suite

2018-10-10 14:08 UTC, acbergan commented
Looks great!

2018-10-10 14:09 UTC, merged